services:
  app-dev:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    container_name: app-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    expose:
      - "5173"
    working_dir: /app
    environment:
       TELEGRAM_BOT_TOKEN_FILE: /run/secrets/tg_bot_token
       TELEGRAM_ORDERS_CHAT_ID_FILE: /run/secrets/tg_orders_chat_id
    secrets:
      - tg_bot_token
      - tg_orders_chat_id
    volumes:
      - /app/node_modules
      - ./app:/app

  # Pocketbase - sqlite, auth, api, admin ui
  pocketbase:
    build:
      context: ./pb
    container_name: pocketbase
    working_dir: /pb
    restart: unless-stopped
    ports:
      - "8090:8090"
    expose:
      - "8090"
    volumes:
      - ./pb/pb_data:/pb/pb_data

secrets:
  tg_bot_token:
    file: ./secrets/tg_bot_token.txt
  tg_orders_chat_id:
    file: ./secrets/tg_orders_chat_id.txt
